# Sandbox For Learning TensorFlow

import tensorflow

In [9]:
import tensorflow as tf

create a variable: x.

In [11]:
x = tf.constant([[1,2,3],[4,5,6]])
print(x)
print(x.shape)
print(x.dtype)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
(2, 3)
<dtype: 'int32'>


In [14]:
print(x + 5)  # adding 5 to each value of x
print(x * 2)  # multiplying each value of x by 2
print(tf.concat([x, x, x], axis=1)) # concatenating the tensors together side by side
print(tf.reduce_sum(x)) # finds the sum of all of the elements in the tensor

tf.Tensor(
[[ 6  7  8]
 [ 9 10 11]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[ 2  4  6]
 [ 8 10 12]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[1 2 3 1 2 3 1 2 3]
 [4 5 6 4 5 6 4 5 6]], shape=(2, 9), dtype=int32)
tf.Tensor(21, shape=(), dtype=int32)
